// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Table("art")]
[Index("IdMedia", "MediaType", "Type", Name = "ix_art")]
public partial class Art
{
    [Key]
    [Column("idArt")]
    public int IdArt { get; set; }

    [Column("idMedia")]
    public int? IdMedia { get; set; }

    [Column("media_type")]
    public string MediaType { get; set; }

    [Column("type")]
    public string Type { get; set; }

    [Column("url")]
    public string Url { get; set; }

    [Column("width")]
    public int? Width { get; set; }

    [Column("height")]
    public int? Height { get; set; }
}