// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Keyless]
[Table("certification_temp")]
public partial class CertificationTemp
{
    [Column("idMedia")]
    public int? IdMedia { get; set; }

    [Column("media_type")]
    public string MediaType { get; set; }

    [Column("name")]
    public string Name { get; set; }
}