// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Keyless]
[Table("certification_link")]
[Index("IdCertification", "MediaType", "IdMedia", Name = "certification_link_1", IsUnique = true)]
[Index("IdMedia", "MediaType", "IdCertification", Name = "certification_link_2", IsUnique = true)]
[Index("MediaType", Name = "certification_link_3")]
public partial class CertificationLink
{
    [Column("idCertification")]
    public int? IdCertification { get; set; }

    [Column("idMedia")]
    public int? IdMedia { get; set; }

    [Column("media_type")]
    public string MediaType { get; set; }
}