// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Table("certification")]
[Index("Name", Name = "ix_certification", IsUnique = true)]
public partial class Certification
{
    [Key]
    [Column("idCertification")]
    public int IdCertification { get; set; }

    [Column("name")]
    public string Name { get; set; }
}