// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Keyless]
[Table("country_link")]
[Index("IdCountry", "MediaType", "IdMedia", Name = "country_link_1", IsUnique = true)]
[Index("IdMedia", "MediaType", "IdCountry", Name = "country_link_2", IsUnique = true)]
[Index("MediaType", Name = "country_link_3")]
public partial class CountryLink
{
    [Column("idCountry")]
    public int? IdCountry { get; set; }

    [Column("idMedia")]
    public int? IdMedia { get; set; }

    [Column("media_type")]
    public string MediaType { get; set; }
}