// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Keyless]
public partial class Episodelist
{
    [Column("idEpisode")]
    public int? IdEpisode { get; set; }

    [Column("idShow")]
    public int? IdShow { get; set; }

    [Column("idFile")]
    public int? IdFile { get; set; }

    [Column("idSource")]
    public int? IdSource { get; set; }

    [Column("episode")]
    public int? Episode { get; set; }

    [Column("title")]
    public string Title { get; set; }

    [Column("originalTitle")]
    public string OriginalTitle { get; set; }

    [Column("new", TypeName = "bool")]
    public bool? New { get; set; }

    [Column("marked", TypeName = "bool")]
    public bool? Marked { get; set; }

    [Column("locked", TypeName = "bool")]
    public bool? Locked { get; set; }

    [Column("season")]
    public int? Season { get; set; }

    [Column("plot")]
    public string Plot { get; set; }

    [Column("aired")]
    public string Aired { get; set; }

    [Column("nfoPath")]
    public string NfoPath { get; set; }

    [Column("playcount")]
    public int? Playcount { get; set; }

    [Column("displaySeason")]
    public int? DisplaySeason { get; set; }

    [Column("displayEpisode")]
    public int? DisplayEpisode { get; set; }

    [Column("dateAdded")]
    public int? DateAdded { get; set; }

    [Column("runtime")]
    public string Runtime { get; set; }

    [Column("videoSource")]
    public string VideoSource { get; set; }

    [Column("hasSub", TypeName = "bool")]
    public bool? HasSub { get; set; }

    [Column("subEpisode")]
    public int? SubEpisode { get; set; }

    [Column("lastPlayed")]
    public int? LastPlayed { get; set; }

    [Column("userRating")]
    public int? UserRating { get; set; }

    [Column("dateModified")]
    public int? DateModified { get; set; }

    [Column("path")]
    public string Path { get; set; }

    [Column("source")]
    public string Source { get; set; }

    [Column("fanartPath")]
    public string FanartPath { get; set; }

    [Column("posterPath")]
    public string PosterPath { get; set; }

    [Column("credits")]
    public byte[] Credits { get; set; }

    [Column("director")]
    public byte[] Director { get; set; }

    [Column("missing")]
    public byte[] Missing { get; set; }

    [Column("uniqueid")]
    public byte[] Uniqueid { get; set; }
}