// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Keyless]
[Table("file_temp")]
public partial class FileTemp
{
    [Column("idMovie")]
    public int? IdMovie { get; set; }

    [Column("path")]
    public string Path { get; set; }
}