// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Keyless]
[Table("genre_link")]
[Index("IdGenre", "MediaType", "IdMedia", Name = "genre_link_1", IsUnique = true)]
[Index("IdMedia", "MediaType", "IdGenre", Name = "genre_link_2", IsUnique = true)]
[Index("MediaType", Name = "genre_link_3")]
public partial class GenreLink
{
    [Column("idGenre")]
    public int? IdGenre { get; set; }

    [Column("idMedia")]
    public int? IdMedia { get; set; }

    [Column("media_type")]
    public string MediaType { get; set; }
}