// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Keyless]
[Table("gueststar_link")]
[Index("IdPerson", "MediaType", "IdMedia", Name = "ix_gueststar_link_1", IsUnique = true)]
[Index("IdMedia", "MediaType", "IdPerson", Name = "ix_gueststar_link_2", IsUnique = true)]
[Index("MediaType", Name = "ix_gueststar_link_3")]
public partial class GueststarLink
{
    [Column("idPerson")]
    public int? IdPerson { get; set; }

    [Column("idMedia")]
    public int? IdMedia { get; set; }

    [Column("media_type")]
    public string MediaType { get; set; }

    [Column("role")]
    public string Role { get; set; }

    [Column("cast_order")]
    public int? CastOrder { get; set; }
}