// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Table("movieset")]
public partial class Movieset
{
    [Key]
    [Column("idSet")]
    public long Id { get; set; }

    [Column("nfoPath")]
    public string NfoPath { get; set; }

    [Column("plot")]
    public string Plot { get; set; }

    [Column("title")]
    public string Title { get; set; }

    [Column("new", TypeName = "bool")]
    public bool New { get; set; }

    [Column("marked", TypeName = "bool")]
    public bool Marked { get; set; }

    [Column("locked", TypeName = "bool")]
    public bool Locked { get; set; }

    [Column("sortMethod")]
    public int SortMethod { get; set; }

    [Column("language")]
    public string Language { get; set; }

    public List<Movie> Movies { get; }
}