// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Keyless]
public partial class Moviesetlist
{
    [Column("idSet")]
    public int? IdSet { get; set; }

    [Column("nfoPath")]
    public string NfoPath { get; set; }

    [Column("plot")]
    public string Plot { get; set; }

    [Column("title")]
    public string Title { get; set; }

    [Column("new", TypeName = "bool")]
    public bool? New { get; set; }

    [Column("marked", TypeName = "bool")]
    public bool? Marked { get; set; }

    [Column("locked", TypeName = "bool")]
    public bool? Locked { get; set; }

    [Column("sortMethod")]
    public int? SortMethod { get; set; }

    [Column("language")]
    public string Language { get; set; }

    [Column("bannerPath")]
    public string BannerPath { get; set; }

    [Column("clearartPath")]
    public string ClearartPath { get; set; }

    [Column("clearlogoPath")]
    public string ClearlogoPath { get; set; }

    [Column("discartPath")]
    public string DiscartPath { get; set; }

    [Column("fanartPath")]
    public string FanartPath { get; set; }

    [Column("keyartPath")]
    public string KeyartPath { get; set; }

    [Column("landscapePath")]
    public string LandscapePath { get; set; }

    [Column("posterPath")]
    public string PosterPath { get; set; }

    [Column("movieCount")]
    public byte[] MovieCount { get; set; }

    [Column("movieTitles")]
    public byte[] MovieTitles { get; set; }

    [Column("uniqueid")]
    public byte[] Uniqueid { get; set; }
}