// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Table("moviesource")]
[Index("Path", Name = "UniqueMovieSourcePath", IsUnique = true)]
public partial class Moviesource : EFSourceBase
{
    [Column("scanRecursive", TypeName = "bool")]
    public bool ScanRecursive { get; set; }

    [Column("useFolderName", TypeName = "bool")]
    public bool UseFolderName { get; set; }

    [Column("getYear", TypeName = "bool")]
    public bool GetYear { get; set; }
}