// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Table("movie")]
[Index("FileId", "IdMovie", Name = "ix_movie_file_1", IsUnique = true)]
[Index("IdMovie", "FileId", Name = "ix_movie_file_2", IsUnique = true)]
public partial class Movie
{
    [Key]
    [Column("idMovie")]
    public long Id { get; set; }

    [Column("idSource")]
    public int SourceId { get; set; }

    public Moviesource Source { get; set; }

    [Column("idFile")]
    public int FileId { get; set; }

    public MyFile File { get; set; }

    public List<MovieRoleLink> MovieRoles { get; set; }

    [Column("isSingle", TypeName = "bool")]
    public bool? IsSingle { get; set; }

    [Column("hasSub", TypeName = "bool")]
    public bool HasSub { get; set; }

    [Column("new", TypeName = "bool")]
    public bool New { get; set; }

    [Column("marked", TypeName = "bool")]
    public bool Marked { get; set; }

    [Column("locked", TypeName = "bool")]
    public bool? Locked { get; set; }

    [Column("title")]
    public string Title { get; set; }

    [Column("originalTitle")]
    public string OriginalTitle { get; set; }

    [Column("mpaa")]
    public string Mpaa { get; set; }

    [Column("top250")]
    public int? Top250 { get; set; }

    [Column("outline")]
    public string Outline { get; set; }

    [Column("plot")]
    public string Plot { get; set; }

    [Column("tagline")]
    public string Tagline { get; set; }

    [Column("runtime")]
    public string Runtime { get; set; }

    [Column("premiered")]
    public string Premiered { get; set; }

    [Column("playcount")]
    public int? Playcount { get; set; }

    [Column("trailer")]
    public string Trailer { get; set; }

    [Column("ethumbsPath")]
    public string EthumbsPath { get; set; }

    [Column("nfoPath")]
    public string NfoPath { get; set; }

    [Column("trailerPath")]
    public string TrailerPath { get; set; }

    [Column("subPath")]
    public string SubPath { get; set; }

    [Column("outOfTolerance", TypeName = "bool")]
    public bool? OutOfTolerance { get; set; }

    [Column("videoSource")]
    public string VideoSource { get; set; }

    [Column("sortTitle")]
    public string SortTitle { get; set; }

    [Column("dateAdded")]
    public int? DateAdded { get; set; }

    [Column("efanartsPath")]
    public string EfanartsPath { get; set; }

    [Column("themePath")]
    public string ThemePath { get; set; }

    [Column("dateModified")]
    public int? DateModified { get; set; }

    [Column("markCustom1", TypeName = "bool")]
    public bool MarkCustom1 { get; set; }

    [Column("markCustom2", TypeName = "bool")]
    public bool MarkCustom2 { get; set; }

    [Column("markCustom3", TypeName = "bool")]
    public bool MarkCustom3 { get; set; }

    [Column("markCustom4", TypeName = "bool")]
    public bool MarkCustom4 { get; set; }

    [Column("hasSet", TypeName = "bool")]
    public bool HasSet { get; set; }

    [Column("lastPlayed")]
    public int? LastPlayed { get; set; }

    [Column("language")]
    public string Language { get; set; }

    [Column("userRating")]
    public int UserRating { get; set; }
}