// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[PrimaryKey("MovieId", "StreamId")]
[Table("MoviesVStreams")]
public partial class MoviesVstream
{
    [Key]
    [Column("MovieID")]
    public int MovieId { get; set; }

    [Key]
    [Column("StreamID")]
    public int StreamId { get; set; }

    [Column("Video_Width")]
    public string VideoWidth { get; set; }

    [Column("Video_Height")]
    public string VideoHeight { get; set; }

    [Column("Video_Codec")]
    public string VideoCodec { get; set; }

    [Column("Video_Duration")]
    public string VideoDuration { get; set; }

    [Column("Video_ScanType")]
    public string VideoScanType { get; set; }

    [Column("Video_AspectDisplayRatio")]
    public string VideoAspectDisplayRatio { get; set; }

    [Column("Video_Language")]
    public string VideoLanguage { get; set; }

    [Column("Video_LongLanguage")]
    public string VideoLongLanguage { get; set; }

    [Column("Video_Bitrate")]
    public string VideoBitrate { get; set; }

    [Column("Video_MultiViewCount")]
    public string VideoMultiViewCount { get; set; }

    [Column("Video_MultiViewLayout")]
    public string VideoMultiViewLayout { get; set; }

    [Column("Video_StereoMode")]
    public string VideoStereoMode { get; set; }

    [Column("Video_FileSize")]
    public int VideoFileSize { get; set; }
}