// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Keyless]
[Table("movieset_link")]
[Index("IdSet", "IdMovie", Name = "movieset_link_1", IsUnique = true)]
[Index("IdMovie", "IdSet", Name = "movieset_link_2", IsUnique = true)]
public partial class MoviesetLink
{
    [Column("idSet")]
    public int IdSet { get; set; }

    [Column("idMovie")]
    public int IdMovie { get; set; }
}