// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

/// <summary>
/// Named MyFile to not conflict with System.IO
/// </summary>
[Table("file")]
[Index("Path", Name = "UniqueFilename", IsUnique = true)]
public partial class MyFile
{
    [Key]
    [Column("idFile")]
    public int IdFile { get; set; }

    [Required]
    [Column("path")]
    public string Path { get; set; }

    [Column("originalFileName")]
    public string OriginalFileName { get; set; }

    [Column("fileSize")]
    public int? FileSize { get; set; }
}