// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Net.Sockets;
using EmberAPICSharp;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

public partial class MyVideosContext : DbContext
{
    private string _dbPath;

    /// <summary>
    /// This constructor is used by the EF Core Power Tools to generate the model.
    /// </summary>
    public MyVideosContext()
    {
        _dbPath = @"C:\Users\dyste\SynologyDrive\Coding\Ember-MM-Newscraper\EmberMM - Debug - AnyCPU\net8.0-windows\Profiles\Default\MyVideos49.emm";
    }
    public MyVideosContext(string dbPath)
    {
        _dbPath = dbPath;
    }    
    
    public virtual DbSet<Art> Arts { get; set; }

    public virtual DbSet<Certification> Certifications { get; set; }

    public virtual DbSet<CertificationLink> CertificationLinks { get; set; }

    public virtual DbSet<CertificationTemp> CertificationTemps { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<CountryLink> CountryLinks { get; set; }

    public virtual DbSet<CreatorLink> CreatorLinks { get; set; }

    public virtual DbSet<DirectorLink> DirectorLinks { get; set; }

    public virtual DbSet<Episode> Episodes { get; set; }

    public virtual DbSet<Episodelist> Episodelists { get; set; }

    public virtual DbSet<Excludedpath> Excludedpaths { get; set; }

    public virtual DbSet<MyFile> Files { get; set; }

    public virtual DbSet<FileTemp> FileTemps { get; set; }

    public virtual DbSet<Genre> Genres { get; set; }

    public virtual DbSet<GenreLink> GenreLinks { get; set; }

    public virtual DbSet<GueststarLink> GueststarLinks { get; set; }

    public virtual DbSet<Movie> Movies { get; set; }

    public virtual DbSet<Movielist> Movielists { get; set; }

    public virtual DbSet<MoviesAstream> MoviesAstreams { get; set; }

    public virtual DbSet<MoviesSub> MoviesSubs { get; set; }

    public virtual DbSet<MoviesVstream> MoviesVstreams { get; set; }

    public virtual DbSet<Movieset> Moviesets { get; set; }
    
    public virtual DbSet<Moviesetlist> Moviesetlists { get; set; }

    public virtual DbSet<Moviesource> Moviesources { get; set; }

    public virtual DbSet<Person> People { get; set; }

    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<Season> Seasons { get; set; }

    public virtual DbSet<Seasonlist> Seasonlists { get; set; }

    public virtual DbSet<Streamdetail> Streamdetails { get; set; }

    public virtual DbSet<Studio> Studios { get; set; }

    public List<Studio> GetStudios(EFEnums.MediaType mediaType, long mediaId)
    {
        // TODO change to join query
        var idlist = StudioLinks.Where(e => e.MediaType == mediaType && e.IdMedia == mediaId).Select(e => e.Id).ToList();
        return Studios.Where(e => idlist.Contains(e.Id)).ToList();

    }

    public virtual DbSet<StudioLink> StudioLinks { get; set; }

    public virtual DbSet<Tag> Tags { get; set; }

    public List<Tag> GetTags(EFEnums.MediaType mediaType, long mediaId)
    {
        // TODO change to join query
        var idlist = TagLinks.Where(e => e.MediaType == mediaType && e.IdMedia == mediaId).Select(e => e.Id).ToList();
        return Tags.Where(e => idlist.Contains(e.Id)).ToList();

    }

    public virtual DbSet<TagLink> TagLinks { get; set; }

    public virtual DbSet<Tvastream> Tvastreams { get; set; }

    public virtual DbSet<Tvshow> Tvshows { get; set; }

    public virtual DbSet<TvshowLink> TvshowLinks { get; set; }

    public virtual DbSet<Tvshowlist> Tvshowlists { get; set; }

    public virtual DbSet<Tvshowsource> Tvshowsources { get; set; }

    public virtual DbSet<Tvsub> Tvsubs { get; set; }

    public virtual DbSet<Tvvstream> Tvvstreams { get; set; }

    public virtual DbSet<Uniqueid> Uniqueids { get; set; }

    public virtual DbSet<WriterLink> WriterLinks { get; set; }

    public virtual DbSet<MovieRole> MovieRoleLinks { get; set; }
    public virtual DbSet<TvshowRole> TvshowRoleLinks { get; set; }
    public virtual DbSet<EpisodeRole> EpisodeRoleLinks { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite($"Data Source={_dbPath}");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Art>(entity =>
        {
            
        });

        modelBuilder.Entity<Certification>(entity =>
        {
            
        });

        modelBuilder.Entity<Country>(entity =>
        {
            
        });

        modelBuilder.Entity<Episode>(entity =>
        {
            entity.Property(e => e.New).HasDefaultValue(false);
            entity.HasOne(e => e.File);
        });

        modelBuilder.Entity<Episodelist>(entity =>
        {
            entity.ToView("episodelist");
        });

        modelBuilder.Entity<MyFile>(entity =>
        {
            
        });

        modelBuilder.Entity<Genre>(entity =>
        {
            
        });        

        modelBuilder.Entity<Movie>(entity =>
        {
            entity.Property(e => e.FileId).HasDefaultValue(-1);
            entity.HasOne(e => e.File);
        });

        modelBuilder.Entity<Movielist>(entity =>
        {
            entity.ToView("movielist");
        });

        modelBuilder.Entity<Movieset>(entity =>
        {
            
        });

        modelBuilder.Entity<Moviesetlist>(entity =>
        {
            entity.ToView("moviesetlist");
        });

        modelBuilder.Entity<Moviesource>(entity =>
        {
            
            entity.Property(e => e.GetYear).HasDefaultValue(true);
            entity.Property(e => e.Language).HasDefaultValue("en-US");
        });

        modelBuilder.Entity<Person>(entity =>
        {
            entity.HasMany(e => e.Movies).WithMany(e=>e.Persons).UsingEntity<MovieRole>();
            entity.HasMany(e => e.Tvshows).WithMany(e=>e.Persons).UsingEntity<TvshowRole>();
            entity.HasMany(e => e.Episodes).WithMany(e=>e.Persons).UsingEntity<EpisodeRole>();
        });

        modelBuilder.Entity<Season>(entity =>
        {
            
        });

        modelBuilder.Entity<Seasonlist>(entity =>
        {
            entity.ToView("seasonlist");
        });

        modelBuilder.Entity<Studio>(entity =>
        {
            
        });

        modelBuilder.Entity<Tag>(entity =>
        {
            
        });

        modelBuilder.Entity<Tvshow>(entity =>
        {
            entity.Property(e => e.New).HasDefaultValue(false);
        });

        modelBuilder.Entity<Tvshowlist>(entity =>
        {
            entity.ToView("tvshowlist");
        });

        modelBuilder.Entity<Tvshowsource>(entity =>
        {
            entity.Property(e => e.Language).HasDefaultValue("en-US");
        });

        modelBuilder.Entity<Uniqueid>(entity =>
        {
            entity.Property(e => e.IsDefault).HasDefaultValue(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

public class RoleLink
{
    public long PersonId { get; set; }
    public Person Person { get; set; }
    public string Role { get; set; }
    public bool RoleSpecified => !string.IsNullOrEmpty(Role);
    public int CastOrder { get; set; }

    [NotMapped]
    public string Name => Person.Name;
    [NotMapped]
    public string URLOriginal => Person.URLOriginal;

    [Obsolete]
    [NotMapped] 
    public long ID => PersonId;
}
public class MovieRole : RoleLink
{
    public long MovieId { get; set; }
    public Movie Movie { get; set; }
}

public class TvshowRole : RoleLink
{
    public long TvshowId { get; set; }
    public Tvshow Tvshow { get; set; }
}

public class EpisodeRole : RoleLink
{
    public long EpisodeId { get; set; }
    public Episode Episode { get; set; }
}