// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml.Serialization;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Table("person")]
[Serializable]
public partial class Person
{
    // TODO: Remember to add role and order into the database intermediate
    [Key]
    [Column("idPerson")]
    [XmlIgnore]
    public long Id { get; set; } = -1;

    [Required]
    [Column("name")]
    [XmlElement("name")]
    public string Name { get; set; }

    [NotMapped]
    [XmlIgnore]
    public bool NameSpecified => !string.IsNullOrEmpty(Name);
    
    [Column("thumb")]
    [XmlElement("thumb")]
    public string URLOriginal { get; set; }

    [NotMapped]
    [XmlIgnore]
    public bool URLOriginalSpecified => !string.IsNullOrEmpty(URLOriginal);

    [XmlElement("imdbid")]
    [Column("imdbid")]
    public string IMDbId { get; set; } = string.Empty;

    [XmlElement("tmdbid")]
    [Column("tmdbid")]
    public string TMDbId { get; set; } = string.Empty;

    [XmlElement("tvdbid")]
    [Column("tvdbid")]
    public string TVDbId { get; set; } = string.Empty;

    public List<MovieRole> MovieRoles { get; set; }
    public List<Movie> Movies { get; set; }
    public List<TvshowRole> TvshowRoles { get; set; }
    public List<Tvshow> Tvshows { get; set; }
    public List<EpisodeRole> EpisodeRoles { get; set; }
    public List<Episode> Episodes { get; set; }



}