// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Table("person")]
public partial class Person
{
    [Key]
    [Column("idPerson")]
    public int IdPerson { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Column("thumb")]
    public string Thumb { get; set; }
}