// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using static EmberAPICSharp.EFEnums;

namespace EmberAPI.EFModels;

[Table("rating")]
[Index("IdMedia", "MediaType", Name = "ix_rating")]
public partial class Rating
{
    [Key]
    [Column("idRating")]
    public int Id { get; set; }

    [Column("idMedia")]
    public int IdMedia { get; set; }

    [Column("media_type")]
    public MediaType MediaType { get; set; }

    [Column("rating_type")]
    public string RatingType { get; set; }

    [Column("rating_max")]
    public int RatingMax { get; set; }

    [Column("rating")]
    public double Rating1 { get; set; }

    [Column("votes")]
    public int Votes { get; set; }

    [Column("isDefault", TypeName = "boolean")]
    public bool IsDefault { get; set; }
}