// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Keyless]
public partial class Seasonlist
{
    [Column("idSeason")]
    public int? IdSeason { get; set; }

    [Column("idShow")]
    public int? IdShow { get; set; }

    [Column("season")]
    public int? Season { get; set; }

    [Column("title")]
    public string Title { get; set; }

    [Column("locked", TypeName = "bool")]
    public bool? Locked { get; set; }

    [Column("marked", TypeName = "bool")]
    public bool? Marked { get; set; }

    [Column("new", TypeName = "bool")]
    public bool? New { get; set; }

    [Column("aired")]
    public string Aired { get; set; }

    [Column("plot")]
    public string Plot { get; set; }

    [Column("bannerPath")]
    public string BannerPath { get; set; }

    [Column("fanartPath")]
    public string FanartPath { get; set; }

    [Column("landscapePath")]
    public string LandscapePath { get; set; }

    [Column("posterPath")]
    public string PosterPath { get; set; }

    [Column("episodes")]
    public byte[] Episodes { get; set; }

    [Column("playcount")]
    public byte[] Playcount { get; set; }

    [Column("hasWatched")]
    public byte[] HasWatched { get; set; }

    [Column("newEpisodes")]
    public byte[] NewEpisodes { get; set; }

    [Column("missing")]
    public byte[] Missing { get; set; }

    [Column("uniqueid")]
    public byte[] Uniqueid { get; set; }
}