// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Table("season")]
[Index("IdShow", "Season1", Name = "ix_season", IsUnique = true)]
public partial class Season
{
    [Key]
    [Column("idSeason")]
    public int IdSeason { get; set; }

    [Column("idShow")]
    public int? IdShow { get; set; }

    [Column("season")]
    public int? Season1 { get; set; }

    [Column("title")]
    public string Title { get; set; }

    [Column("locked", TypeName = "bool")]
    public bool Locked { get; set; }

    [Column("marked", TypeName = "bool")]
    public bool Marked { get; set; }

    [Column("new", TypeName = "bool")]
    public bool New { get; set; }

    [Column("aired")]
    public string Aired { get; set; }

    [Column("plot")]
    public string Plot { get; set; }
}