// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmberAPI.EFModels
{    
    public class EFSourceBase
    {

        [Column("exclude", TypeName = "bool")]
        public bool Exclude { get; set; }
        [Key]
        [Column("idSource")]
        public int IdSource { get; set; }

        [NotMapped]
        public bool IDSpecified => IdSource != -1;


        [Column("isSingle", TypeName = "bool")]
        public bool IsSingle { get; set; }

        [Required]
        [Column("language")]
        public string Language { get; set; }

        [NotMapped]
        public bool LanguageSpecified => !string.IsNullOrEmpty(Language);


        [Required]
        [Column("name")]
        public string Name { get; set; }

        [Required]
        [Column("path")]
        public string Path { get; set; }
    }
}