// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Keyless]
[Table("streamdetail")]
[Index("IdFile", Name = "ix_streamdetail")]
public partial class Streamdetail
{
    [Column("idFile")]
    public int? IdFile { get; set; }

    [Column("streamType")]
    public int? StreamType { get; set; }

    [Column("videoCodec")]
    public string VideoCodec { get; set; }

    [Column("videoAspect", TypeName = "float")]
    public double? VideoAspect { get; set; }

    [Column("videoBitrate")]
    public int? VideoBitrate { get; set; }

    [Column("videoLanguage")]
    public string VideoLanguage { get; set; }

    [Column("videoWidth")]
    public int? VideoWidth { get; set; }

    [Column("videoHeight")]
    public int? VideoHeight { get; set; }

    [Column("videoScantype")]
    public string VideoScantype { get; set; }

    [Column("videoDuration")]
    public int? VideoDuration { get; set; }

    [Column("videoMultiViewCount")]
    public int? VideoMultiViewCount { get; set; }

    [Column("videoMultiViewLayout")]
    public string VideoMultiViewLayout { get; set; }

    [Column("videoStereoMode")]
    public string VideoStereoMode { get; set; }

    [Column("videoBitDepth")]
    public int? VideoBitDepth { get; set; }

    [Column("videoChromaSubsampling")]
    public string VideoChromaSubsampling { get; set; }

    [Column("videoColourPrimaries")]
    public string VideoColourPrimaries { get; set; }

    [Column("audioCodec")]
    public string AudioCodec { get; set; }

    [Column("audioChannels")]
    public int? AudioChannels { get; set; }

    [Column("audioBitrate")]
    public int? AudioBitrate { get; set; }

    [Column("audioLanguage")]
    public string AudioLanguage { get; set; }

    [Column("audioBitDepth")]
    public int? AudioBitDepth { get; set; }

    [Column("audioAdditionalFeatures")]
    public string AudioAdditionalFeatures { get; set; }

    [Column("subtitleLanguage")]
    public string SubtitleLanguage { get; set; }

    [Column("subtitleForced", TypeName = "boolean")]
    public bool? SubtitleForced { get; set; }

    [Column("subtitlePath")]
    public string SubtitlePath { get; set; }
}