// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using EmberAPICSharp;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Keyless]
[Table("studio_link")]
[Index("Id", "MediaType", "IdMedia", Name = "ix_studio_link_1", IsUnique = true)]
[Index("IdMedia", "MediaType", "Id", Name = "ix_studio_link_2", IsUnique = true)]
[Index("MediaType", Name = "ix_studio_link_3")]
public partial class StudioLink
{
    [Column("idStudio")]
    public long Id { get; set; }

    [Column("idMedia")]
    public int? IdMedia { get; set; }

    [Column("media_type")]
    public EFEnums.MediaType MediaType { get; set; }
}