// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using EmberAPICSharp;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Table("studio")]
public partial class Studio
{
    [Key]
    [Column("idStudio")]
    public long Id { get; set; }

    [Column("name")]
    public string Name { get; set; }    
}