// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Table("tag")]
[Index("Name", Name = "ix_tag_1", IsUnique = true)]
public partial class Tag
{
    [Key]
    [Column("idTag")]
    public int IdTag { get; set; }

    [Column("name")]
    public string Name { get; set; }
}