// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[PrimaryKey("TvepId", "StreamId")]
[Table("TVAStreams")]
public partial class Tvastream
{
    [Key]
    [Column("TVEpID")]
    public int TvepId { get; set; }

    [Key]
    [Column("StreamID")]
    public int StreamId { get; set; }

    [Column("Audio_Language")]
    public string AudioLanguage { get; set; }

    [Column("Audio_LongLanguage")]
    public string AudioLongLanguage { get; set; }

    [Column("Audio_Codec")]
    public string AudioCodec { get; set; }

    [Column("Audio_Channel")]
    public string AudioChannel { get; set; }

    [Column("Audio_Bitrate")]
    public string AudioBitrate { get; set; }
}