// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Keyless]
public partial class Tvshowlist
{
    [Column("idShow")]
    public int? IdShow { get; set; }

    [Column("idSource")]
    public int? IdSource { get; set; }

    [Column("new", TypeName = "bool")]
    public bool? New { get; set; }

    [Column("marked", TypeName = "bool")]
    public bool? Marked { get; set; }

    [Column("path")]
    public string Path { get; set; }

    [Column("locked", TypeName = "bool")]
    public bool? Locked { get; set; }

    [Column("episodeGuide")]
    public string EpisodeGuide { get; set; }

    [Column("plot")]
    public string Plot { get; set; }

    [Column("premiered")]
    public string Premiered { get; set; }

    [Column("mpaa")]
    public string Mpaa { get; set; }

    [Column("nfoPath")]
    public string NfoPath { get; set; }

    [Column("language")]
    public string Language { get; set; }

    [Column("episodeOrdering")]
    public int? EpisodeOrdering { get; set; }

    [Column("status")]
    public string Status { get; set; }

    [Column("themePath")]
    public string ThemePath { get; set; }

    [Column("efanartsPath")]
    public string EfanartsPath { get; set; }

    [Column("runtime")]
    public string Runtime { get; set; }

    [Column("title")]
    public string Title { get; set; }

    [Column("episodeSorting")]
    public int? EpisodeSorting { get; set; }

    [Column("sortTitle")]
    public string SortTitle { get; set; }

    [Column("originalTitle")]
    public string OriginalTitle { get; set; }

    [Column("userRating")]
    public int? UserRating { get; set; }

    [Column("dateModified")]
    public int? DateModified { get; set; }

    [Column("dateAdded")]
    public int? DateAdded { get; set; }

    [Column("sortedTitle")]
    public byte[] SortedTitle { get; set; }

    [Column("source")]
    public string Source { get; set; }

    [Column("bannerPath")]
    public string BannerPath { get; set; }

    [Column("characterartPath")]
    public string CharacterartPath { get; set; }

    [Column("clearartPath")]
    public string ClearartPath { get; set; }

    [Column("clearlogoPath")]
    public string ClearlogoPath { get; set; }

    [Column("fanartPath")]
    public string FanartPath { get; set; }

    [Column("keyartPath")]
    public string KeyartPath { get; set; }

    [Column("landscapePath")]
    public string LandscapePath { get; set; }

    [Column("posterPath")]
    public string PosterPath { get; set; }

    [Column("country")]
    public byte[] Country { get; set; }

    [Column("creator")]
    public byte[] Creator { get; set; }

    [Column("genre")]
    public byte[] Genre { get; set; }

    [Column("studio")]
    public byte[] Studio { get; set; }

    [Column("tag")]
    public byte[] Tag { get; set; }

    [Column("episodes")]
    public byte[] Episodes { get; set; }

    [Column("playcount")]
    public byte[] Playcount { get; set; }

    [Column("hasWatched")]
    public byte[] HasWatched { get; set; }

    [Column("newEpisodes")]
    public byte[] NewEpisodes { get; set; }

    [Column("markedEpisodes")]
    public byte[] MarkedEpisodes { get; set; }

    [Column("lockedEpisodes")]
    public byte[] LockedEpisodes { get; set; }

    [Column("uniqueid")]
    public byte[] Uniqueid { get; set; }
}