// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Table("tvshow")]
[Index("Path", Name = "UniquePath", IsUnique = true)]
public partial class Tvshow
{
    [Key]
    [Column("idShow")]
    public int IdShow { get; set; }

    [Column("idSource")]
    public int IdSource { get; set; }

    [Column("new", TypeName = "bool")]
    public bool? New { get; set; }

    [Column("marked", TypeName = "bool")]
    public bool Marked { get; set; }

    [Required]
    [Column("path")]
    public string Path { get; set; }

    [Column("locked", TypeName = "bool")]
    public bool Locked { get; set; }

    [Column("episodeGuide")]
    public string EpisodeGuide { get; set; }

    [Column("plot")]
    public string Plot { get; set; }

    [Column("premiered")]
    public string Premiered { get; set; }

    [Column("mpaa")]
    public string Mpaa { get; set; }

    [Column("nfoPath")]
    public string NfoPath { get; set; }

    [Column("language")]
    public string Language { get; set; }

    [Column("episodeOrdering")]
    public int EpisodeOrdering { get; set; }

    [Column("status")]
    public string Status { get; set; }

    [Column("themePath")]
    public string ThemePath { get; set; }

    [Column("efanartsPath")]
    public string EfanartsPath { get; set; }

    [Column("runtime")]
    public string Runtime { get; set; }

    [Column("title")]
    public string Title { get; set; }

    [Column("episodeSorting")]
    public int EpisodeSorting { get; set; }

    [Column("sortTitle")]
    public string SortTitle { get; set; }

    [Column("originalTitle")]
    public string OriginalTitle { get; set; }

    [Column("userRating")]
    public int UserRating { get; set; }

    [Column("dateModified")]
    public int? DateModified { get; set; }

    [Column("dateAdded")]
    public int? DateAdded { get; set; }
}