// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Table("tvshowsource")]
[Index("Path", Name = "UniqueTVShowSourcePath", IsUnique = true)]
public partial class Tvshowsource
{
    [Key]
    [Column("idSource")]
    public int IdSource { get; set; }

    [Required]
    [Column("path")]
    public string Path { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Required]
    [Column("language")]
    public string Language { get; set; }

    [Column("episodeOrdering")]
    public int EpisodeOrdering { get; set; }

    [Column("exclude", TypeName = "bool")]
    public bool Exclude { get; set; }

    [Column("episodeSorting")]
    public int EpisodeSorting { get; set; }

    [Column("isSingle", TypeName = "bool")]
    public bool IsSingle { get; set; }
}