// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Keyless]
[Table("tvshow_link")]
[Index("IdShow", "IdMovie", Name = "ix_tvshow_link_1", IsUnique = true)]
[Index("IdMovie", "IdShow", Name = "ix_tvshow_link_2", IsUnique = true)]
public partial class TvshowLink
{
    [Column("idShow")]
    public int? IdShow { get; set; }

    [Column("idMovie")]
    public int? IdMovie { get; set; }
}