// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[Table("tvshowsource")]
[Index("Path", Name = "UniqueTVShowSourcePath", IsUnique = true)]
public partial class Tvshowsource : EFSourceBase
{      
    [Column("episodeOrdering")]
    public EpisodeOrdering EpisodeOrdering { get; set; }    

    [Column("episodeSorting")]
    public EpisodeSorting EpisodeSorting { get; set; }    
}

/// <summary>
/// Enum representing valid TV series ordering.
/// </summary>
public enum EpisodeOrdering : int
{
    Standard = 0,
    DVD = 1,
    Absolute = 2,
    DayOfYear = 3
}

/// <summary>
/// Enum representing Order of displaying Episodes
/// </summary>
public enum EpisodeSorting : int
{
    Episode = 0,
    Aired = 1
}