// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmberAPI.EFModels;

[PrimaryKey("TvepId", "StreamId")]
[Table("TVSubs")]
public partial class Tvsub
{
    [Key]
    [Column("TVEpID")]
    public int TvepId { get; set; }

    [Key]
    [Column("StreamID")]
    public int StreamId { get; set; }

    [Column("Subs_Language")]
    public string SubsLanguage { get; set; }

    [Column("Subs_LongLanguage")]
    public string SubsLongLanguage { get; set; }

    [Column("Subs_Type")]
    public string SubsType { get; set; }

    [Column("Subs_Path")]
    public string SubsPath { get; set; }

    [Column("Subs_Forced", TypeName = "BOOL")]
    public bool SubsForced { get; set; }
}