// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using static EmberAPICSharp.EFEnums;

namespace EmberAPI.EFModels;

[Table("uniqueid")]
[Index("IdMedia", "MediaType", "Type", Name = "ix_uniqueid1")]
[Index("MediaType", "Value", Name = "ix_uniqueid2")]
public partial class Uniqueid
{
    [Key]
    [Column("idUniqueID")]
    public int Id { get; set; }

    [Column("idMedia")]
    public int IdMedia { get; set; }

    [Column("media_type")]
    public MediaType MediaType { get; set; }

    [Column("value")]
    public string Value { get; set; }

    [Column("type")]
    public string Type { get; set; }

    [Column("isDefault", TypeName = "boolean")]
    public bool IsDefault { get; set; }
}